//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Teacher.Properties;

using System;
using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
internal sealed class Resources
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    private Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager
        => resourceMan ??= new ResourceManager("QuizApp.Teacher.Properties.Resources", typeof(Resources).Assembly);

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? string.Empty;
    internal static string QuizTitleLabel => ResourceManager.GetString("QuizTitleLabel", resourceCulture) ?? string.Empty;
    internal static string LoadButtonText => ResourceManager.GetString("LoadButtonText", resourceCulture) ?? string.Empty;
    internal static string SaveButtonText => ResourceManager.GetString("SaveButtonText", resourceCulture) ?? string.Empty;
    internal static string ClearButtonText => ResourceManager.GetString("ClearButtonText", resourceCulture) ?? string.Empty;
    internal static string AddQuestionButtonText => ResourceManager.GetString("AddQuestionButtonText", resourceCulture) ?? string.Empty;
    internal static string QuestionLabelFormat => ResourceManager.GetString("QuestionLabelFormat", resourceCulture) ?? string.Empty;
    internal static string QuestionTitlePlaceholder => ResourceManager.GetString("QuestionTitlePlaceholder", resourceCulture) ?? string.Empty;
    internal static string PlusPointsLabel => ResourceManager.GetString("PlusPointsLabel", resourceCulture) ?? string.Empty;
    internal static string MinusPointsLabel => ResourceManager.GetString("MinusPointsLabel", resourceCulture) ?? string.Empty;
    internal static string AddAnswerButtonText => ResourceManager.GetString("AddAnswerButtonText", resourceCulture) ?? string.Empty;
    internal static string AnswerTitlePlaceholder => ResourceManager.GetString("AnswerTitlePlaceholder", resourceCulture) ?? string.Empty;
    internal static string AnswerCorrectText => ResourceManager.GetString("AnswerCorrectText", resourceCulture) ?? string.Empty;
    internal static string MoveUpText => ResourceManager.GetString("MoveUpText", resourceCulture) ?? string.Empty;
    internal static string MoveDownText => ResourceManager.GetString("MoveDownText", resourceCulture) ?? string.Empty;
    internal static string RemoveText => ResourceManager.GetString("RemoveText", resourceCulture) ?? string.Empty;
    internal static string PasswordDialogTitle => ResourceManager.GetString("PasswordDialogTitle", resourceCulture) ?? string.Empty;
    internal static string PasswordLabel => ResourceManager.GetString("PasswordLabel", resourceCulture) ?? string.Empty;
    internal static string OkButtonText => ResourceManager.GetString("OkButtonText", resourceCulture) ?? string.Empty;
    internal static string CancelButtonText => ResourceManager.GetString("CancelButtonText", resourceCulture) ?? string.Empty;
    internal static string LoadDialogTitle => ResourceManager.GetString("LoadDialogTitle", resourceCulture) ?? string.Empty;
    internal static string SaveDialogTitle => ResourceManager.GetString("SaveDialogTitle", resourceCulture) ?? string.Empty;
    internal static string QuizFileFilter => ResourceManager.GetString("QuizFileFilter", resourceCulture) ?? string.Empty;
    internal static string ValidationProblemTitle => ResourceManager.GetString("ValidationProblemTitle", resourceCulture) ?? string.Empty;
    internal static string InfoTitle => ResourceManager.GetString("InfoTitle", resourceCulture) ?? string.Empty;
    internal static string WarningTitle => ResourceManager.GetString("WarningTitle", resourceCulture) ?? string.Empty;
    internal static string ErrorTitle => ResourceManager.GetString("ErrorTitle", resourceCulture) ?? string.Empty;
    internal static string DefaultQuizTitle => ResourceManager.GetString("DefaultQuizTitle", resourceCulture) ?? string.Empty;
}
